project_id = "etadhhphjzztketgxnxl"

[functions.analyze-content]
verify_jwt = true

[functions.api-access]
verify_jwt = true

[functions.assign-badges]
verify_jwt = true

[functions.categorize-investor]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-donation]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.export-user-data]
verify_jwt = true

[functions.generate-narrative]
verify_jwt = true

[functions.generate-recommendations]
verify_jwt = true

[functions.score-assessment]
verify_jwt = true

[functions.advanced-scoring]
verify_jwt = true

[functions.score-engine]
verify_jwt = true

[functions.send-donation-confirmation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-report-email]
verify_jwt = true

[functions.setup-2fa]
verify_jwt = true

[functions.sync-crm]
verify_jwt = true

[functions.sync-zoho]
verify_jwt = true

[functions.upload-pitch-deck]
verify_jwt = true

[functions.webhook-handler]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.process-background-jobs]
verify_jwt = false

[functions.send-scheduled-report]
verify_jwt = true
