// Comprehensive mock data for Investor and Startup Directories
// Will be synced with Supabase and Zoho CRM

export interface InvestorDirectoryItem {
  id: string;
  name: string;
  organization: string;
  title: string;
  email: string;
  linkedin_url?: string;
  sectors: string[];
  stages: string[];
  regions: string[];
  ticket_min: number;
  ticket_max: number;
  bio: string;
  portfolio_companies?: string[];
  notable_investments?: string;
  investment_thesis?: string;
  is_verified: boolean;
  is_active: boolean;
}

export interface StartupDirectoryItem {
  id: string;
  company_name: string;
  tagline: string;
  description: string;
  website?: string;
  email?: string;
  founder_name: string;
  founder_email?: string;
  founder_linkedin?: string;
  team_size: string;
  sector: string;
  stage: string;
  location: string;
  region: string;
  funding_raised?: number;
  funding_goal?: number;
  current_mrr?: number;
  has_revenue: boolean;
  readiness_score: number;
  key_metrics?: Record<string, any>;
  is_verified: boolean;
  is_active: boolean;
  seeking_funding: boolean;
}

export const mockInvestorDirectory: InvestorDirectoryItem[] = [
  {
    id: 'inv-001',
    name: 'Sarah Chen',
    organization: 'Sequoia Capital',
    title: 'Partner',
    email: 'sarah.chen@sequoia.com',
    linkedin_url: 'https://linkedin.com/in/sarahchen',
    sectors: ['FinTech', 'B2B SaaS', 'AI/ML'],
    stages: ['Seed', 'Series A'],
    regions: ['North America', 'Asia'],
    ticket_min: 500000,
    ticket_max: 5000000,
    bio: 'Focused on early-stage B2B software companies with strong unit economics and recurring revenue models. 15+ years in venture capital.',
    portfolio_companies: ['Stripe', 'DoorDash', 'Airbnb', 'MongoDB'],
    investment_thesis: 'Backing exceptional founders building category-defining companies with sustainable competitive advantages',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-002',
    name: 'Marcus Thompson',
    organization: 'Andreessen Horowitz',
    title: 'General Partner',
    email: 'm.thompson@a16z.com',
    linkedin_url: 'https://linkedin.com/in/marcusthompson',
    sectors: ['HealthTech', 'BioTech', 'Digital Health'],
    stages: ['Series A', 'Series B'],
    regions: ['North America'],
    ticket_min: 2000000,
    ticket_max: 15000000,
    bio: 'Leading investments in consumer health and wellness technology with proven market traction and regulatory pathway.',
    portfolio_companies: ['Ro', 'Hims & Hers', 'Noom', 'Oscar Health'],
    investment_thesis: 'Investing in digital health companies democratizing access to healthcare through technology',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-003',
    name: 'Priya Sharma',
    organization: 'Accel Partners',
    title: 'Managing Partner',
    email: 'priya@accel.com',
    linkedin_url: 'https://linkedin.com/in/priyasharma',
    sectors: ['EdTech', 'Enterprise Software', 'Productivity'],
    stages: ['Pre-Seed', 'Seed', 'Series A'],
    regions: ['Asia', 'Europe'],
    ticket_min: 250000,
    ticket_max: 3000000,
    bio: 'Passionate about education technology and enterprise solutions transforming emerging markets. Former Google executive.',
    portfolio_companies: ['Freshworks', 'BrowserStack', 'Swiggy', 'Flipkart'],
    investment_thesis: 'Backing technology that empowers businesses and individuals in high-growth markets',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-004',
    name: 'David Rodriguez',
    organization: 'Lightspeed Venture Partners',
    title: 'Principal',
    email: 'david.r@lightspeedvp.com',
    linkedin_url: 'https://linkedin.com/in/davidrodriguez',
    sectors: ['Climate Tech', 'Clean Energy', 'Sustainability'],
    stages: ['Seed', 'Series A'],
    regions: ['Europe', 'North America'],
    ticket_min: 1000000,
    ticket_max: 8000000,
    bio: 'Climate tech advocate investing in sustainable solutions with scalable business models and measurable environmental impact.',
    portfolio_companies: ['Sila Nanotechnologies', 'Lilium', 'Notpla', 'Rivian'],
    investment_thesis: 'Funding breakthrough technologies addressing climate change while generating strong returns',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-005',
    name: 'Emily Watson',
    organization: 'Index Ventures',
    title: 'Venture Partner',
    email: 'emily@indexventures.com',
    linkedin_url: 'https://linkedin.com/in/emilywatson',
    sectors: ['Marketplace', 'Consumer', 'Creator Economy'],
    stages: ['Series A', 'Series B'],
    regions: ['Europe', 'Global'],
    ticket_min: 3000000,
    ticket_max: 12000000,
    bio: 'Former marketplace founder with deep expertise in network effects, platform economics, and community-driven businesses.',
    portfolio_companies: ['Deliveroo', 'Farfetch', 'Wolt', 'Depop'],
    investment_thesis: 'Investing in marketplace platforms with strong unit economics and sustainable competitive moats',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-006',
    name: 'James Kim',
    organization: 'Tiger Global',
    title: 'Partner',
    email: 'james@tigerglobal.com',
    linkedin_url: 'https://linkedin.com/in/jameskim',
    sectors: ['FinTech', 'Crypto/Web3', 'Financial Services'],
    stages: ['Series B', 'Series C', 'Growth'],
    regions: ['North America', 'Asia'],
    ticket_min: 10000000,
    ticket_max: 50000000,
    bio: 'Growth-stage investor specializing in fintech innovation and blockchain infrastructure with proven global expansion.',
    portfolio_companies: ['Coinbase', 'Chime', 'Checkout.com', 'Robinhood'],
    investment_thesis: 'Backing fintech companies disrupting traditional financial services at scale',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-007',
    name: 'Maria Garcia',
    organization: 'GV (Google Ventures)',
    title: 'Investment Partner',
    email: 'maria@gv.com',
    linkedin_url: 'https://linkedin.com/in/mariagarcia',
    sectors: ['AI/ML', 'Enterprise Software', 'Developer Tools'],
    stages: ['Seed', 'Series A', 'Series B'],
    regions: ['North America', 'Europe'],
    ticket_min: 1500000,
    ticket_max: 10000000,
    bio: 'Former Google engineer investing in AI-first companies and developer infrastructure. Deep technical background.',
    portfolio_companies: ['Anthropic', 'GitLab', 'Cockroach Labs', 'Vercel'],
    investment_thesis: 'Supporting founders building the next generation of intelligent software and developer tools',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-008',
    name: 'Alexander Petrov',
    organization: 'Coatue Management',
    title: 'Vice President',
    email: 'alex@coatue.com',
    linkedin_url: 'https://linkedin.com/in/alexanderpetrov',
    sectors: ['B2B SaaS', 'Infrastructure', 'Security'],
    stages: ['Series A', 'Series B', 'Growth'],
    regions: ['Global'],
    ticket_min: 5000000,
    ticket_max: 30000000,
    bio: 'Focus on enterprise software companies with best-in-class retention and expansion metrics. Former enterprise sales leader.',
    portfolio_companies: ['Snowflake', 'Datadog', 'CrowdStrike', 'UiPath'],
    investment_thesis: 'Investing in enterprise infrastructure that becomes mission-critical for large organizations',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-009',
    name: 'Lisa Park',
    organization: 'Insight Partners',
    title: 'Managing Director',
    email: 'lisa.park@insightpartners.com',
    linkedin_url: 'https://linkedin.com/in/lisapark',
    sectors: ['Healthcare', 'Digital Health', 'Life Sciences'],
    stages: ['Series A', 'Series B', 'Series C'],
    regions: ['North America', 'Europe'],
    ticket_min: 8000000,
    ticket_max: 40000000,
    bio: 'Healthcare specialist investing in companies improving patient outcomes through technology and data-driven insights.',
    portfolio_companies: ['Oscar Health', '23andMe', 'Tempus', 'Devoted Health'],
    investment_thesis: 'Backing digital health innovators transforming healthcare delivery and patient access',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-010',
    name: 'Omar Hassan',
    organization: '500 Global',
    title: 'Partner',
    email: 'omar@500global.com',
    linkedin_url: 'https://linkedin.com/in/omarhassan',
    sectors: ['E-commerce', 'Logistics', 'Supply Chain'],
    stages: ['Pre-Seed', 'Seed'],
    regions: ['Middle East', 'Africa', 'Asia'],
    ticket_min: 100000,
    ticket_max: 1000000,
    bio: 'Early-stage investor supporting entrepreneurs in emerging markets with global ambitions and scalable business models.',
    portfolio_companies: ['Jumia', 'Twiga Foods', 'Vezeeta', 'Flutterwave'],
    investment_thesis: 'Investing in digital infrastructure and commerce platforms for underserved markets',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-011',
    name: 'Rachel Cohen',
    organization: 'Bessemer Venture Partners',
    title: 'Partner',
    email: 'rachel@bvp.com',
    linkedin_url: 'https://linkedin.com/in/rachelcohen',
    sectors: ['SaaS', 'Cloud Infrastructure', 'DevOps'],
    stages: ['Series A', 'Series B'],
    regions: ['North America', 'Europe'],
    ticket_min: 4000000,
    ticket_max: 20000000,
    bio: 'Cloud-first investor with expertise in horizontal and vertical SaaS businesses. Pioneered cloud computing thesis.',
    portfolio_companies: ['Twilio', 'SendGrid', 'PagerDuty', 'Shopify'],
    investment_thesis: 'Partnering with founders building the cloud infrastructure and SaaS platforms of tomorrow',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-012',
    name: 'Thomas Mueller',
    organization: 'Atomico',
    title: 'Partner',
    email: 'thomas@atomico.com',
    linkedin_url: 'https://linkedin.com/in/thomasmueller',
    sectors: ['DeepTech', 'Robotics', 'Advanced Manufacturing'],
    stages: ['Series A', 'Series B', 'Growth'],
    regions: ['Europe', 'Global'],
    ticket_min: 7000000,
    ticket_max: 35000000,
    bio: 'Deep tech specialist investing in hardware-software integrated solutions with IP moats and global expansion potential.',
    portfolio_companies: ['UiPath', 'Graphcore', 'Lilium', 'Scandit'],
    investment_thesis: 'Backing breakthrough technologies that push the boundaries of what\'s physically possible',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-013',
    name: 'Jennifer Wu',
    organization: 'First Round Capital',
    title: 'Partner',
    email: 'jennifer@firstround.com',
    linkedin_url: 'https://linkedin.com/in/jenniferwu',
    sectors: ['B2B SaaS', 'Productivity', 'Future of Work'],
    stages: ['Pre-Seed', 'Seed'],
    regions: ['North America'],
    ticket_min: 500000,
    ticket_max: 2000000,
    bio: 'Pre-seed specialist helping first-time founders navigate product-market fit and go-to-market strategy.',
    portfolio_companies: ['Uber', 'Square', 'Notion', 'Roblox'],
    investment_thesis: 'Partnering with ambitious founders at day zero to build iconic companies',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-014',
    name: 'Raj Kapoor',
    organization: 'Mayfield Fund',
    title: 'General Partner',
    email: 'raj@mayfield.com',
    linkedin_url: 'https://linkedin.com/in/rajkapoor',
    sectors: ['Enterprise AI', 'Data Infrastructure', 'Analytics'],
    stages: ['Seed', 'Series A', 'Series B'],
    regions: ['North America', 'Asia'],
    ticket_min: 2000000,
    ticket_max: 12000000,
    bio: 'Data infrastructure investor with deep expertise in AI/ML platforms and enterprise analytics solutions.',
    portfolio_companies: ['Databricks', 'Confluent', 'Amplitude', 'ThoughtSpot'],
    investment_thesis: 'Investing in the data and AI infrastructure powering modern enterprises',
    is_verified: true,
    is_active: true,
  },
  {
    id: 'inv-015',
    name: 'Sophie Laurent',
    organization: 'Balderton Capital',
    title: 'Partner',
    email: 'sophie@balderton.com',
    linkedin_url: 'https://linkedin.com/in/sophielaur ent',
    sectors: ['Consumer', 'E-commerce', 'Retail Tech'],
    stages: ['Series A', 'Series B'],
    regions: ['Europe'],
    ticket_min: 3000000,
    ticket_max: 15000000,
    bio: 'Consumer tech specialist backing European founders building global consumer brands and platforms.',
    portfolio_companies: ['Revolut', 'Citymapper', 'Lovefilm', 'Yoox'],
    investment_thesis: 'Partnering with European entrepreneurs building world-class consumer technology companies',
    is_verified: true,
    is_active: true,
  },
];

export const mockStartupDirectory: StartupDirectoryItem[] = [
  {
    id: 'startup-001',
    company_name: 'VisionAI',
    tagline: 'AI-powered computer vision for manufacturing quality control',
    description: 'We reduce defect rates by 95% using real-time AI visual inspection on production lines. Deployed in 50+ factories across automotive, electronics, and pharmaceutical manufacturing.',
    website: 'https://visionai.example.com',
    email: 'contact@visionai.example.com',
    founder_name: 'Marcus Johnson',
    founder_email: 'marcus@visionai.example.com',
    founder_linkedin: 'https://linkedin.com/in/marcusjohnson',
    team_size: '28',
    sector: 'AI/ML',
    stage: 'Series A',
    location: 'San Francisco, CA',
    region: 'North America',
    funding_raised: 5000000,
    funding_goal: 3000000,
    current_mrr: 85000,
    has_revenue: true,
    readiness_score: 85,
    key_metrics: {
      arr: '$1,020,000',
      customers: 52,
      defect_detection_rate: '95%',
      growth_rate: '18% MoM',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-002',
    company_name: 'HealthPulse',
    tagline: 'Remote patient monitoring for chronic disease management',
    description: 'FDA-cleared wearable + AI platform helping doctors monitor chronic patients remotely. Reducing hospital readmissions by 40% and improving patient outcomes.',
    website: 'https://healthpulse.example.com',
    email: 'hello@healthpulse.example.com',
    founder_name: 'Dr. Samantha Lee',
    founder_email: 'samantha@healthpulse.example.com',
    founder_linkedin: 'https://linkedin.com/in/drsamanthalee',
    team_size: '15',
    sector: 'HealthTech',
    stage: 'Seed',
    location: 'Boston, MA',
    region: 'North America',
    funding_raised: 1500000,
    funding_goal: 2000000,
    current_mrr: 42000,
    has_revenue: true,
    readiness_score: 78,
    key_metrics: {
      patients_monitored: 5000,
      hospital_partners: 12,
      readmission_reduction: '40%',
      growth_rate: '25% MoM',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-003',
    company_name: 'GreenCharge',
    tagline: 'Solar-powered EV charging network for sustainable transportation',
    description: 'Building the largest carbon-neutral EV charging network. 200+ stations installed across major cities, powered by renewable energy with smart grid integration.',
    website: 'https://greencharge.example.com',
    email: 'info@greencharge.example.com',
    founder_name: 'Elena Rodriguez',
    founder_email: 'elena@greencharge.example.com',
    founder_linkedin: 'https://linkedin.com/in/elenarodriguez',
    team_size: '65',
    sector: 'Climate Tech',
    stage: 'Series B',
    location: 'Austin, TX',
    region: 'North America',
    funding_raised: 25000000,
    funding_goal: 10000000,
    current_mrr: 420000,
    has_revenue: true,
    readiness_score: 89,
    key_metrics: {
      arr: '$5,040,000',
      charging_stations: 200,
      active_users: 15000,
      carbon_offset: '2,500 tons/year',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-004',
    company_name: 'EduFlow',
    tagline: 'AI tutor personalizing K-12 education at scale',
    description: 'Adaptive learning platform using AI to personalize lessons for each student. Improving test scores by 32% on average across 45 schools.',
    website: 'https://eduflow.example.com',
    email: 'support@eduflow.example.com',
    founder_name: 'Jason Park',
    founder_email: 'jason@eduflow.example.com',
    founder_linkedin: 'https://linkedin.com/in/jasonpark',
    team_size: '12',
    sector: 'EdTech',
    stage: 'Seed',
    location: 'Palo Alto, CA',
    region: 'North America',
    funding_raised: 800000,
    funding_goal: 1500000,
    current_mrr: 28000,
    has_revenue: true,
    readiness_score: 75,
    key_metrics: {
      students: 8500,
      schools: 45,
      test_score_improvement: '32%',
      growth_rate: '30% MoM',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-005',
    company_name: 'SecureAPI',
    tagline: 'Real-time API security platform preventing data breaches',
    description: 'AI-powered API threat detection and response system. Protecting $2B+ in transactions daily and preventing attacks in <50ms response time.',
    website: 'https://secureapi.example.com',
    email: 'security@secureapi.example.com',
    founder_name: 'Rachel Kim',
    founder_email: 'rachel@secureapi.example.com',
    founder_linkedin: 'https://linkedin.com/in/rachelkim',
    team_size: '32',
    sector: 'Cybersecurity',
    stage: 'Series A',
    location: 'New York, NY',
    region: 'North America',
    funding_raised: 8000000,
    funding_goal: 5000000,
    current_mrr: 125000,
    has_revenue: true,
    readiness_score: 82,
    key_metrics: {
      arr: '$1,500,000',
      enterprise_clients: 78,
      attacks_blocked: '2,000,000+',
      response_time: '<50ms',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-006',
    company_name: 'FarmTech',
    tagline: 'IoT + AI for precision agriculture and crop optimization',
    description: 'Sensors and ML models helping farmers increase yields by 25% while reducing water usage by 40%. Active on 500+ farms globally.',
    website: 'https://farmtech.example.com',
    email: 'hello@farmtech.example.com',
    founder_name: 'Carlos Santos',
    founder_email: 'carlos@farmtech.example.com',
    founder_linkedin: 'https://linkedin.com/in/carlossantos',
    team_size: '24',
    sector: 'AgriTech',
    stage: 'Series A',
    location: 'Des Moines, IA',
    region: 'North America',
    funding_raised: 6000000,
    funding_goal: 4000000,
    current_mrr: 75000,
    has_revenue: true,
    readiness_score: 80,
    key_metrics: {
      arr: '$900,000',
      farms: 500,
      yield_increase: '25%',
      water_saved: '40%',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-007',
    company_name: 'CreatorOS',
    tagline: 'All-in-one platform for content creators to monetize',
    description: 'Helping creators monetize through subscriptions, courses, and memberships. 10,000+ creators earning on our platform with 5% take rate.',
    website: 'https://creatorsos.example.com',
    email: 'team@creatorsos.example.com',
    founder_name: 'Mia Thompson',
    founder_email: 'mia@creatorsos.example.com',
    founder_linkedin: 'https://linkedin.com/in/miathompson',
    team_size: '18',
    sector: 'Creator Economy',
    stage: 'Seed',
    location: 'Los Angeles, CA',
    region: 'North America',
    funding_raised: 2000000,
    funding_goal: 2500000,
    current_mrr: 55000,
    has_revenue: true,
    readiness_score: 76,
    key_metrics: {
      creators: 10000,
      gmv: '$15,000,000',
      take_rate: '5%',
      growth_rate: '28% MoM',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-008',
    company_name: 'SupplyChain.ai',
    tagline: 'AI-powered supply chain optimization reducing costs 20%',
    description: 'ML platform reducing supply chain costs by 20% and stockouts by 75%. Serving manufacturers and retailers with predictive analytics.',
    website: 'https://supplychain-ai.example.com',
    email: 'info@supplychain-ai.example.com',
    founder_name: 'Wei Zhang',
    founder_email: 'wei@supplychain-ai.example.com',
    founder_linkedin: 'https://linkedin.com/in/weizhang',
    team_size: '35',
    sector: 'Logistics',
    stage: 'Series A',
    location: 'Seattle, WA',
    region: 'North America',
    funding_raised: 10000000,
    funding_goal: 6000000,
    current_mrr: 145000,
    has_revenue: true,
    readiness_score: 83,
    key_metrics: {
      arr: '$1,740,000',
      enterprise_clients: 42,
      cost_reduction: '20%',
      stockout_reduction: '75%',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-009',
    company_name: 'FinFlow',
    tagline: 'Embedded finance platform for vertical SaaS companies',
    description: 'White-label financial services (banking, lending, payments) for B2B software companies. 80+ SaaS partners processing $1.2B annually.',
    website: 'https://finflow.example.com',
    email: 'partnerships@finflow.example.com',
    founder_name: 'Ahmed Hassan',
    founder_email: 'ahmed@finflow.example.com',
    founder_linkedin: 'https://linkedin.com/in/ahmedhassan',
    team_size: '58',
    sector: 'FinTech',
    stage: 'Series B',
    location: 'New York, NY',
    region: 'North America',
    funding_raised: 28000000,
    funding_goal: 15000000,
    current_mrr: 380000,
    has_revenue: true,
    readiness_score: 87,
    key_metrics: {
      arr: '$4,560,000',
      saas_partners: 80,
      payment_volume: '$1,200,000,000',
      nrr: '80%',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-010',
    company_name: 'QuantumSafe',
    tagline: 'Post-quantum cryptography for enterprise security',
    description: 'Preparing enterprises for quantum computing threats with NIST-approved algorithms. Protecting critical infrastructure and sensitive data.',
    website: 'https://quantumsafe.example.com',
    email: 'security@quantumsafe.example.com',
    founder_name: 'Dr. Lisa Chen',
    founder_email: 'lisa@quantumsafe.example.com',
    founder_linkedin: 'https://linkedin.com/in/drlisachen',
    team_size: '22',
    sector: 'Cybersecurity',
    stage: 'Series A',
    location: 'Washington, DC',
    region: 'North America',
    funding_raised: 12000000,
    funding_goal: 7000000,
    current_mrr: 95000,
    has_revenue: true,
    readiness_score: 80,
    key_metrics: {
      arr: '$1,140,000',
      enterprise_clients: 28,
      fortune_500: 5,
      certifications: 'NIST, SOC 2, ISO 27001',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-011',
    company_name: 'BioScan',
    tagline: 'AI-powered early cancer detection from blood tests',
    description: 'Single blood test detecting 12 cancer types at stage 1 with 92% accuracy. Clinical trials in progress at Johns Hopkins and Mayo Clinic.',
    website: 'https://bioscan.example.com',
    email: 'clinical@bioscan.example.com',
    founder_name: 'Dr. Robert Williams',
    founder_email: 'robert@bioscan.example.com',
    founder_linkedin: 'https://linkedin.com/in/drrobertwilliams',
    team_size: '40',
    sector: 'BioTech',
    stage: 'Series A',
    location: 'Baltimore, MD',
    region: 'North America',
    funding_raised: 18000000,
    funding_goal: 12000000,
    current_mrr: 0,
    has_revenue: false,
    readiness_score: 82,
    key_metrics: {
      detection_accuracy: '92%',
      clinical_trials: 'Phase 2',
      hospital_partners: 3,
      patents: 12,
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-012',
    company_name: 'CloudOps Pro',
    tagline: 'DevOps automation reducing cloud costs by 40%',
    description: 'AI-driven cloud cost optimization and DevOps automation. Saving enterprises millions on AWS, Azure, and GCP through intelligent resource management.',
    website: 'https://cloudopspro.example.com',
    email: 'sales@cloudopspro.example.com',
    founder_name: 'Nina Patel',
    founder_email: 'nina@cloudopspro.example.com',
    founder_linkedin: 'https://linkedin.com/in/ninapatel',
    team_size: '26',
    sector: 'B2B SaaS',
    stage: 'Series A',
    location: 'Seattle, WA',
    region: 'North America',
    funding_raised: 7000000,
    funding_goal: 4000000,
    current_mrr: 88000,
    has_revenue: true,
    readiness_score: 79,
    key_metrics: {
      arr: '$1,056,000',
      customers: 65,
      avg_savings: '40%',
      nrr: '125%',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-013',
    company_name: 'TalentMatch AI',
    tagline: 'AI-powered recruitment platform matching candidates to roles',
    description: 'Using machine learning to match candidates with jobs 10x faster than traditional methods. 500+ companies using our platform for technical hiring.',
    website: 'https://talentmatch.example.com',
    email: 'hello@talentmatch.example.com',
    founder_name: 'Kevin O\'Brien',
    founder_email: 'kevin@talentmatch.example.com',
    founder_linkedin: 'https://linkedin.com/in/kevinobrien',
    team_size: '20',
    sector: 'HR Tech',
    stage: 'Series A',
    location: 'London, UK',
    region: 'Europe',
    funding_raised: 5000000,
    funding_goal: 3500000,
    current_mrr: 62000,
    has_revenue: true,
    readiness_score: 77,
    key_metrics: {
      arr: '$744,000',
      companies: 500,
      placements: 2500,
      time_to_hire: '10 days avg',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-014',
    company_name: 'FoodTrace',
    tagline: 'Blockchain-powered food supply chain transparency',
    description: 'Track food from farm to table with blockchain verification. Reducing food fraud by 80% and improving supply chain efficiency for major retailers.',
    website: 'https://foodtrace.example.com',
    email: 'contact@foodtrace.example.com',
    founder_name: 'Isabella Martinez',
    founder_email: 'isabella@foodtrace.example.com',
    founder_linkedin: 'https://linkedin.com/in/isabellamartinez',
    team_size: '19',
    sector: 'Supply Chain',
    stage: 'Seed',
    location: 'Chicago, IL',
    region: 'North America',
    funding_raised: 2500000,
    funding_goal: 2000000,
    current_mrr: 35000,
    has_revenue: true,
    readiness_score: 74,
    key_metrics: {
      arr: '$420,000',
      retailers: 25,
      products_tracked: '500,000+',
      fraud_reduction: '80%',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
  {
    id: 'startup-015',
    company_name: 'NeuralDesign',
    tagline: 'AI-powered design automation for product teams',
    description: 'Generate production-ready UI designs from text descriptions. Reducing design-to-development time by 60% for product teams at scale companies.',
    website: 'https://neuraldesign.example.com',
    email: 'team@neuraldesign.example.com',
    founder_name: 'Oliver Schmidt',
    founder_email: 'oliver@neuraldesign.example.com',
    founder_linkedin: 'https://linkedin.com/in/oliverschmidt',
    team_size: '14',
    sector: 'Design Tools',
    stage: 'Seed',
    location: 'Berlin, Germany',
    region: 'Europe',
    funding_raised: 1800000,
    funding_goal: 2000000,
    current_mrr: 38000,
    has_revenue: true,
    readiness_score: 73,
    key_metrics: {
      arr: '$456,000',
      customers: 180,
      designs_generated: '50,000+',
      time_saved: '60%',
    },
    is_verified: true,
    is_active: true,
    seeking_funding: true,
  },
];