// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etadhhphjzztketgxnxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0YWRoaHBoanp6dGtldGd4bnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTU4MjYsImV4cCI6MjA2NjUzMTgyNn0.5HeP0MBlTEPvHXG8K-tC58geh_33ItHzTyRLtMtKL0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);